# Generated by Django 3.0.5 on 2020-05-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReviewID",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ReviewDateTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewDateTime", models.DateTimeField()),
                (
                    "review_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_analysis.ReviewID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cultureAndValuesRating", models.FloatField()),
                ("seniorLeadershipRating", models.FloatField()),
                ("compensationAndBenefitsRating", models.FloatField()),
                ("careerOpportunitiesRating", models.FloatField()),
                ("workLifeBalanceRating", models.FloatField()),
                ("overallNumeric", models.FloatField()),
                ("ceoRating", models.IntegerField()),
                (
                    "review_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_analysis.ReviewID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobTitle", models.TextField()),
                ("location", models.TextField()),
                ("currentJob", models.BooleanField()),
                ("lengthOfEmployment", models.TextField()),
                ("country", models.TextField()),
                (
                    "review_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_analysis.ReviewID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessOutlook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("businessOutlook", models.TextField()),
                ("overall", models.TextField()),
                (
                    "review_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_analysis.ReviewID",
                    ),
                ),
            ],
        ),
    ]
