# Generated by Django 3.0.5 on 2020-05-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_analysis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewdatetime",
            old_name="reviewDateTime",
            new_name="reviewdatetime",
        ),
    ]
