# Generated by Django 3.0.5 on 2020-05-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_analysis", "0002_auto_20200503_1903"),
    ]

    operations = [
        migrations.RemoveField(model_name="ratings", name="ceoRating",),
    ]
