# Generated by Django 3.0.6 on 2020-05-08 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0003_remove_ratings_ceorating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinfo',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='reviewdatetime',
            name='review_id',
        ),
        migrations.DeleteModel(
            name='BusinessOutlook',
        ),
        migrations.DeleteModel(
            name='JobInfo',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.DeleteModel(
            name='ReviewDateTime',
        ),
        migrations.DeleteModel(
            name='ReviewID',
        ),
    ]
